apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yml
- namespace.yml
- service.yml
- dr.yml
- vs.yml
- vs-api.yml
- se.yml
- secret.yml
- cm.yml
- ../gateway/

namespace: ${NAMESPACE}
images:
- name: localhost/opentelemetry-collector-contrib
  newName: quay.io/otel/opentelemetry-collector-contrib
- name: localhost/app:frontend
  newName: quay.io/infrastructure/app
  newTag: frontend
